server:
  port: 8081
  servlet:
    context-path: '/mps-user/'

spring:
  application:
    name: mps-user-service
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:postgresql://localhost:5432/mps-user
    username: user
    password: user1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.mps: TRACE
    root: INFO
    org.hibernate: INFO

mps:
  api:
    url:
      course: 'http://mps-course-service/mps-course'
  broker:
    exchange:
      userEvent: mps.userevent
  serviceRegistry:
    username: serviceregistry
    password: 'mps1234'
  auth:
    jwtSecret: McQfTjWnZr4u7x!A%D*G-KaPdRgUkXp2s5v8y/B?E(H+MbQeThVmYq3t6w9z$C&F
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${mps.serviceRegistry.username}:${mps.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
